### Openml
In Python, OpenML is mainly used to discover, download, and share ML datasets, tasks, and results—super handy for experiments, benchmarking, and learning ML properly.

In [ ]:
%pip install openml

Collecting openml
  Downloading openml-0.15.1-py3-none-any.whl.metadata (10 kB)
Collecting liac-arff>=2.4.0 (from openml)
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting xmltodict (from openml)
  Downloading xmltodict-1.0.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.32.5)
Requirement already satisfied: scikit-learn>=0.18 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.7.0)
Requirement already satisfied: python-dateutil in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.8.2)
Requirement already satisfied: pandas>=1.0.0 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.0.3)
Requirement already satisfied: scipy>=0.13.3 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.11.1)
Requirement already satisfied: numpy>=1.6.2 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.26.4)
Collecting minio (from openml)
  Downloading minio-7.2.20-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pyarrow in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (11.0.0)
Requirement already satisfied: tqdm in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (4.67.1)
Requirement already satisfied: packaging in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (23.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\sajindra\anaconda3\lib\site-packages (from pandas>=1.0.0->openml) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sajindra\anaconda3\lib\site-packages (from pandas>=1.0.0->openml) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sajindra\anaconda3\lib\site-packages (from python-dateutil->openml) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sajindra\anaconda3\lib\site-packages (from scikit-learn>=0.18->openml) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sajindra\anaconda3\lib\site-packages (from scikit-learn>=0.18->openml) (3.6.0)
Requirement already satisfied: argon2-cffi in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (21.3.0)
Requirement already satisfied: certifi in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (2023.7.22)
Collecting pycryptodome (from minio->openml)
  Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (4.15.0)
Requirement already satisfied: urllib3 in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (1.26.16)
Requirement already satisfied: argon2-cffi-bindings in c:\users\sajindra\anaconda3\lib\site-packages (from argon2-cffi->minio->openml) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\sajindra\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (1.15.1)
Requirement already satisfied: pycparser in c:\users\sajindra\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (2.21)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sajindra\anaconda3\lib\site-packages (from requests->openml) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sajindra\anaconda3\lib\site-packages (from requests->openml) (3.4)
Requirement already satisfied: colorama in c:\users\sajindra\anaconda3\lib\site-packages (from tqdm->openml) (0.4.6)
Downloading openml-0.15.1-py3-none-any.whl (160 kB)
Downloading minio-7.2.20-py3-none-any.whl (93 kB)
Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 14.0 MB/s  0:00:00
Downloading xmltodict-1.0.2-py3-none-any.whl (13 kB)
Building wheels for collected packages: liac-arff
  Building wheel for liac-arff (pyproject.toml): started
  Building wheel for liac-arff (pyproject.toml): finished with status 'done'
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11782 sha256=9921c6d72a204d76ae4db5e1a26a56c7e81b9229d0d4ea86ffb65316f371d912
  Stored in directory: c:\users\sajindra\appdata\local\pip\cache\wheels\00\23\31\5e562fce1f95aabe57f2a7320d07433ba1cd152bcde2f6a002
Successfully built liac-arff
Installing collected packages: xmltodict, pycryptodome, liac-arff, minio, openml

   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   ---------------- ----------------------- 2/5 [liac-arff]
   ------------------------ --------------- 3/5 [minio]
   -------------------------------- ------- 4/5 [openml]
   -------------------------------- ------- 4/5 [openml]
   -------------------------------- ------- 4/5 [openml]
   ---------------------------------------- 5/5 [openml]

Successfully installed liac-arff-2.5.0 minio-7.2.20 openml-0.15.1 pycryptodome-3.23.0 xmltodict-1.0.2
Note: you may need to restart the kernel to use updated packages.

In [7]:
import openml

In [24]:
# check the datasets with ≤ 10,000 rows i
df = openml.datasets.list_datasets(
    output_format="dataframe",
    number_instances=100
)

df_multiclass = df[df["NumberOfClasses"] >= 2]

df_multiclass

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
461,461,analcatdata_creditscore,1,2,active,ARFF,73.0,6.0,27.0,2.0,7.0,100.0,0.0,0.0,3.0,4.0
716,716,fri_c3_100_50,2,2,active,ARFF,62.0,2.0,38.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
726,726,fri_c2_100_5,2,2,active,ARFF,60.0,2.0,40.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
754,754,fri_c0_100_5,2,2,active,ARFF,54.0,2.0,46.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
762,762,fri_c2_100_10,2,2,active,ARFF,55.0,2.0,45.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
768,768,fri_c3_100_25,2,2,active,ARFF,55.0,2.0,45.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
775,775,fri_c2_100_25,2,2,active,ARFF,57.0,2.0,43.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
783,783,fri_c3_100_10,2,2,active,ARFF,60.0,2.0,40.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
789,789,fri_c1_100_10,2,2,active,ARFF,53.0,2.0,47.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
808,808,fri_c0_100_10,2,2,active,ARFF,55.0,2.0,45.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
812,812,fri_c1_100_25,2,2,active,ARFF,53.0,2.0,47.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
828,828,fri_c4_100_100,2,2,active,ARFF,53.0,2.0,47.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
829,829,fri_c1_100_5,2,2,active,ARFF,55.0,2.0,45.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
850,850,fri_c0_100_50,2,2,active,ARFF,51.0,2.0,49.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
865,865,analcatdata_neavote,2,2,active,ARFF,93.0,3.0,7.0,2.0,3.0,100.0,0.0,0.0,1.0,2.0
868,868,fri_c4_100_25,2,2,active,ARFF,54.0,2.0,46.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
875,875,analcatdata_chlamydia,2,2,active,ARFF,81.0,10.0,19.0,2.0,4.0,100.0,0.0,0.0,0.0,4.0
876,876,fri_c1_100_50,2,2,active,ARFF,56.0,2.0,44.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
878,878,fri_c4_100_10,2,2,active,ARFF,53.0,2.0,47.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
889,889,fri_c0_100_25,2,2,active,ARFF,50.0,2.0,50.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
916,916,fri_c3_100_5,2,2,active,ARFF,56.0,2.0,44.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
922,922,fri_c2_100_50,2,2,active,ARFF,58.0,2.0,42.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
932,932,fri_c4_100_50,2,2,active,ARFF,56.0,2.0,44.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
1463,1463,blogger,1,64,active,ARFF,68.0,5.0,32.0,2.0,6.0,100.0,0.0,0.0,0.0,6.0
1473,1473,fertility,1,64,active,ARFF,88.0,2.0,12.0,2.0,10.0,100.0,0.0,0.0,9.0,1.0
41157,41157,arcene,2,1478,active,ARFF,56.0,2.0,44.0,2.0,10001.0,100.0,0.0,0.0,10000.0,1.0
42763,42763,kits-subset,2,9186,active,arff,51.0,NaN,49.0,2.0,27649.0,100.0,0.0,0.0,0.0,0.0
42766,42766,kits-subset,4,9186,active,arff,52.0,NaN,48.0,2.0,27649.0,100.0,0.0,0.0,27648.0,1.0
44573,44573,arcene_seed_0_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44574,44574,arcene_seed_1_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44575,44575,arcene_seed_2_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44576,44576,arcene_seed_3_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44577,44577,arcene_seed_4_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
46379,46379,analcatdata_creditscore,2,44331,active,arff,73.0,NaN,27.0,2.0,7.0,100.0,0.0,0.0,3.0,2.0
46544,46544,dataset_analcatdata_creditscore,2,44331,active,arff,73.0,NaN,27.0,2.0,7.0,100.0,0.0,0.0,6.0,1.0
46717,46717,biosses,1,25914,active,arff,16.0,NaN,1.0,20.0,5.0,100.0,0.0,0.0,0.0,0.0

In [30]:
df = openml.datasets.list_datasets(output_format="dataframe")

df[df["name"].str.lower() == "iris"]

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
61,61,iris,1,1,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
969,969,iris,3,2,active,ARFF,100.0,2.0,50.0,2.0,5.0,150.0,0.0,0.0,4.0,1.0
41510,41510,iris,9,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41511,41511,iris,10,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41567,41567,iris,11,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41568,41568,iris,12,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41582,41582,iris,13,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41583,41583,iris,14,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41996,41996,iris,15,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41997,41997,iris,16,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42002,42002,iris,17,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42003,42003,iris,18,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42010,42010,iris,19,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42011,42011,iris,20,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42015,42015,iris,21,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42016,42016,iris,22,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42020,42020,iris,23,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42021,42021,iris,24,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42025,42025,iris,25,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42026,42026,iris,26,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42030,42030,iris,27,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42031,42031,iris,28,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42035,42035,iris,29,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42036,42036,iris,30,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42040,42040,iris,31,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42041,42041,iris,32,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42045,42045,iris,33,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42046,42046,iris,34,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42050,42050,iris,35,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42051,42051,iris,36,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42055,42055,iris,37,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42056,42056,iris,38,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42065,42065,iris,39,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42066,42066,iris,40,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42070,42070,iris,41,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42071,42071,iris,42,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42091,42091,iris,43,9456,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42097,42097,iris,44,7214,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42098,42098,iris,45,7214,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42661,42661,iris,46,11598,active,arff,NaN,NaN,NaN,NaN,5.0,150.0,0.0,0.0,4.0,0.0
42699,42699,iris,47,348,active,ARFF,NaN,NaN,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42700,42700,iris,48,348,active,ARFF,50.0,NaN,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42851,42851,iris,49,25829,active,ARFF,NaN,NaN,NaN,NaN,7.0,150.0,0.0,0.0,4.0,3.0
42871,42871,iris,50,25829,active,ARFF,NaN,NaN,NaN,NaN,7.0,150.0,0.0,0.0,4.0,3.0
44151,44151,Iris,51,30495,active,arff,50.0,NaN,49.0,3.0,5.0,149.0,0.0,0.0,4.0,0.0
44344,44344,Iris,52,30495,active,arff,50.0,NaN,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0

### Joblib 
joblib is a small but powerful Python library mainly used in ML for saving models, fast loading, and parallel processing

n_jobs answers “how many things can run in parallel? n_jobs does NOT say threads or processes.
Threading is how parallelism is done. Threading is a backend choice in joblib.
backend="threading"   # threads
backend="loky"        # processes (default)

In [31]:
%pip install joblib

Requirement already satisfied: joblib in c:\users\sajindra\anaconda3\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Download metadata using openml
dataset = openml.datasets.get_dataset(61)

In [35]:
dataset

OpenML Dataset
==============
Name.........: iris
Version......: 1
Format.......: ARFF
Upload Date..: 2014-04-06 23:23:39
Licence......: Public
Download URL.: https://openml.org/data/v1/download/61/iris.arff
OpenML URL...: https://www.openml.org/d/61
# of features: None

In [37]:
# Download the actual data
X,y, categorical_indicator, attribute_names = dataset.get_data(
    target=dataset.default_target_attribute
)

# Save dataset locally
df = X.copy()
df["target"] = y

In [38]:
df.head()

   sepallength  sepalwidth  petallength  petalwidth       target
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [40]:
df.shape

(150, 5)