In [178]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.metrics import adjusted_rand_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder, StandardScaler
import time

### Openml
In Python, OpenML is mainly used to discover, download, and share ML datasets, tasks, and results—super handy for experiments, benchmarking, and learning ML properly.

In [135]:
%pip install openml

Requirement already satisfied: openml in c:\users\sajindra\anaconda3\lib\site-packages (0.15.1)
Requirement already satisfied: liac-arff>=2.4.0 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.5.0)
Requirement already satisfied: xmltodict in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.0.2)
Requirement already satisfied: requests in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.32.5)
Requirement already satisfied: scikit-learn>=0.18 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.7.0)
Requirement already satisfied: python-dateutil in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.8.2)
Requirement already satisfied: pandas>=1.0.0 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (2.0.3)
Requirement already satisfied: scipy>=0.13.3 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.11.1)
Requirement already satisfied: numpy>=1.6.2 in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (1.26.4)
Requirement already satisfied: minio in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (7.2.20)
Requirement already satisfied: pyarrow in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (11.0.0)
Requirement already satisfied: tqdm in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (4.67.1)
Requirement already satisfied: packaging in c:\users\sajindra\anaconda3\lib\site-packages (from openml) (23.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\sajindra\anaconda3\lib\site-packages (from pandas>=1.0.0->openml) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sajindra\anaconda3\lib\site-packages (from pandas>=1.0.0->openml) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sajindra\anaconda3\lib\site-packages (from python-dateutil->openml) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sajindra\anaconda3\lib\site-packages (from scikit-learn>=0.18->openml) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sajindra\anaconda3\lib\site-packages (from scikit-learn>=0.18->openml) (3.6.0)
Requirement already satisfied: argon2-cffi in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (21.3.0)
Requirement already satisfied: certifi in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (2023.7.22)
Requirement already satisfied: pycryptodome in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (3.23.0)
Requirement already satisfied: typing-extensions in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (4.15.0)
Requirement already satisfied: urllib3 in c:\users\sajindra\anaconda3\lib\site-packages (from minio->openml) (1.26.16)
Requirement already satisfied: argon2-cffi-bindings in c:\users\sajindra\anaconda3\lib\site-packages (from argon2-cffi->minio->openml) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\sajindra\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (1.15.1)
Requirement already satisfied: pycparser in c:\users\sajindra\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (2.21)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sajindra\anaconda3\lib\site-packages (from requests->openml) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sajindra\anaconda3\lib\site-packages (from requests->openml) (3.4)
Requirement already satisfied: colorama in c:\users\sajindra\anaconda3\lib\site-packages (from tqdm->openml) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [136]:
import openml

In [137]:
# check the datasets with ≤ 10,000 rows i
df = openml.datasets.list_datasets(
    output_format="dataframe",
    number_instances=100
)

df_multiclass = df[df["NumberOfClasses"] >= 2]

df_multiclass

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
461,461,analcatdata_creditscore,1,2,active,ARFF,73.0,6.0,27.0,2.0,7.0,100.0,0.0,0.0,3.0,4.0
716,716,fri_c3_100_50,2,2,active,ARFF,62.0,2.0,38.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
726,726,fri_c2_100_5,2,2,active,ARFF,60.0,2.0,40.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
754,754,fri_c0_100_5,2,2,active,ARFF,54.0,2.0,46.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
762,762,fri_c2_100_10,2,2,active,ARFF,55.0,2.0,45.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
768,768,fri_c3_100_25,2,2,active,ARFF,55.0,2.0,45.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
775,775,fri_c2_100_25,2,2,active,ARFF,57.0,2.0,43.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
783,783,fri_c3_100_10,2,2,active,ARFF,60.0,2.0,40.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
789,789,fri_c1_100_10,2,2,active,ARFF,53.0,2.0,47.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
808,808,fri_c0_100_10,2,2,active,ARFF,55.0,2.0,45.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
812,812,fri_c1_100_25,2,2,active,ARFF,53.0,2.0,47.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
828,828,fri_c4_100_100,2,2,active,ARFF,53.0,2.0,47.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
829,829,fri_c1_100_5,2,2,active,ARFF,55.0,2.0,45.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
850,850,fri_c0_100_50,2,2,active,ARFF,51.0,2.0,49.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
865,865,analcatdata_neavote,2,2,active,ARFF,93.0,3.0,7.0,2.0,3.0,100.0,0.0,0.0,1.0,2.0
868,868,fri_c4_100_25,2,2,active,ARFF,54.0,2.0,46.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
875,875,analcatdata_chlamydia,2,2,active,ARFF,81.0,10.0,19.0,2.0,4.0,100.0,0.0,0.0,0.0,4.0
876,876,fri_c1_100_50,2,2,active,ARFF,56.0,2.0,44.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
878,878,fri_c4_100_10,2,2,active,ARFF,53.0,2.0,47.0,2.0,11.0,100.0,0.0,0.0,10.0,1.0
889,889,fri_c0_100_25,2,2,active,ARFF,50.0,2.0,50.0,2.0,26.0,100.0,0.0,0.0,25.0,1.0
916,916,fri_c3_100_5,2,2,active,ARFF,56.0,2.0,44.0,2.0,6.0,100.0,0.0,0.0,5.0,1.0
922,922,fri_c2_100_50,2,2,active,ARFF,58.0,2.0,42.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
932,932,fri_c4_100_50,2,2,active,ARFF,56.0,2.0,44.0,2.0,51.0,100.0,0.0,0.0,50.0,1.0
1463,1463,blogger,1,64,active,ARFF,68.0,5.0,32.0,2.0,6.0,100.0,0.0,0.0,0.0,6.0
1473,1473,fertility,1,64,active,ARFF,88.0,2.0,12.0,2.0,10.0,100.0,0.0,0.0,9.0,1.0
41157,41157,arcene,2,1478,active,ARFF,56.0,2.0,44.0,2.0,10001.0,100.0,0.0,0.0,10000.0,1.0
42763,42763,kits-subset,2,9186,active,arff,51.0,NaN,49.0,2.0,27649.0,100.0,0.0,0.0,0.0,0.0
42766,42766,kits-subset,4,9186,active,arff,52.0,NaN,48.0,2.0,27649.0,100.0,0.0,0.0,27648.0,1.0
44573,44573,arcene_seed_0_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44574,44574,arcene_seed_1_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44575,44575,arcene_seed_2_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44576,44576,arcene_seed_3_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
44577,44577,arcene_seed_4_nrows_2000_nclasses_10_ncols_100...,1,32840,active,arff,56.0,NaN,44.0,2.0,101.0,100.0,0.0,0.0,100.0,1.0
46379,46379,analcatdata_creditscore,2,44331,active,arff,73.0,NaN,27.0,2.0,7.0,100.0,0.0,0.0,3.0,2.0
46544,46544,dataset_analcatdata_creditscore,2,44331,active,arff,73.0,NaN,27.0,2.0,7.0,100.0,0.0,0.0,6.0,1.0
46717,46717,biosses,1,25914,active,arff,16.0,NaN,1.0,20.0,5.0,100.0,0.0,0.0,0.0,0.0

In [138]:
df = openml.datasets.list_datasets(output_format="dataframe")

df[df["name"].str.lower() == "iris"]

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
61,61,iris,1,1,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
969,969,iris,3,2,active,ARFF,100.0,2.0,50.0,2.0,5.0,150.0,0.0,0.0,4.0,1.0
41510,41510,iris,9,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41511,41511,iris,10,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41567,41567,iris,11,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41568,41568,iris,12,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41582,41582,iris,13,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41583,41583,iris,14,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
41996,41996,iris,15,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
41997,41997,iris,16,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42002,42002,iris,17,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42003,42003,iris,18,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42010,42010,iris,19,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42011,42011,iris,20,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42015,42015,iris,21,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42016,42016,iris,22,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42020,42020,iris,23,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42021,42021,iris,24,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42025,42025,iris,25,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42026,42026,iris,26,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42030,42030,iris,27,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42031,42031,iris,28,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42035,42035,iris,29,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42036,42036,iris,30,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42040,42040,iris,31,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42041,42041,iris,32,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42045,42045,iris,33,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42046,42046,iris,34,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42050,42050,iris,35,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42051,42051,iris,36,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42055,42055,iris,37,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42056,42056,iris,38,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42065,42065,iris,39,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42066,42066,iris,40,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42070,42070,iris,41,348,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42071,42071,iris,42,348,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42091,42091,iris,43,9456,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42097,42097,iris,44,7214,active,ARFF,NaN,3.0,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42098,42098,iris,45,7214,active,ARFF,50.0,3.0,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42661,42661,iris,46,11598,active,arff,NaN,NaN,NaN,NaN,5.0,150.0,0.0,0.0,4.0,0.0
42699,42699,iris,47,348,active,ARFF,NaN,NaN,NaN,NaN,5.0,150.0,0.0,0.0,4.0,1.0
42700,42700,iris,48,348,active,ARFF,50.0,NaN,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0
42851,42851,iris,49,25829,active,ARFF,NaN,NaN,NaN,NaN,7.0,150.0,0.0,0.0,4.0,3.0
42871,42871,iris,50,25829,active,ARFF,NaN,NaN,NaN,NaN,7.0,150.0,0.0,0.0,4.0,3.0
44151,44151,Iris,51,30495,active,arff,50.0,NaN,49.0,3.0,5.0,149.0,0.0,0.0,4.0,0.0
44344,44344,Iris,52,30495,active,arff,50.0,NaN,50.0,3.0,5.0,150.0,0.0,0.0,4.0,1.0

In [139]:
# Download metadata using openml
dataset = openml.datasets.get_dataset(61)

In [140]:
dataset

OpenML Dataset
==============
Name.........: iris
Version......: 1
Format.......: ARFF
Upload Date..: 2014-04-06 23:23:39
Licence......: Public
Download URL.: https://openml.org/data/v1/download/61/iris.arff
OpenML URL...: https://www.openml.org/d/61
# of features: None

In [141]:
# Download the actual data
X,y, categorical_indicator, attribute_names = dataset.get_data(
    target=dataset.default_target_attribute
)

# Save dataset locally
df = X.copy()

In [142]:
df.head()

   sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [143]:
df.shape

(150, 4)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

### Prepare data

In [145]:
columns = df.columns
df.dtypes

sepallength    float64
sepalwidth     float64
petallength    float64
petalwidth     float64
dtype: object

### Manually select the columns type

In [146]:
# Define columns types
num_columns = columns
#ordinal_columns = ["education", "risk"]
#ordinal_order = ["primary", "secondary", "tertiary"],     # education
#    ["low", "medium", "high", "very_high"]    # risk
#nominal_columns = []
# bin_cols = ["default", "housing", "loan", "y"]

# Pre-processing
Numeric variables --> scale
Ordinal variables -->  Ordinal encoding
Nominal categorical variables -->  Onehot encoding
Binary(already 0 and 1) -->  onehot encoding

# Preprocess

In [147]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder, MinMaxScaler
from sklearn.cluster import KMeans

In [148]:
preprocessor = ColumnTransformer(
    transformers = [
        ("num", MinMaxScaler(), num_columns),
        #("nominal", OneHotEncoder(handle_unknown="ignore"), nominal_columns),
        #("ordinal", OrdinalEncoder(categories=ordinal_order), ordinal_columns),
        #("bin", "passthrough", bin_cols) # data is already numeric and no need totransform this column
    ]
)

### Joblib 
joblib is a small but powerful Python library mainly used in ML for saving models, fast loading, and parallel processing

n_jobs answers “how many things can run in parallel? n_jobs does NOT say threads or processes.
Threading is how parallelism is done. Threading is a backend choice in joblib.
backend="threading"   # threads
backend="loky"        # processes (default)

In [149]:
%pip install joblib

Requirement already satisfied: joblib in c:\users\sajindra\anaconda3\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [150]:
from joblib import Parallel, delayed
import itertools # to create combinations of hyperparameters

# Define parameters

In [151]:
param_grid = {
    "n_clusters": [2, 3, 4, 5, 6],
    "init": ["k-means++", "random"],
    "n_init": [10, 20],
    "max_iter": [300, 500]
}

param_combinations =list(itertools.product(
    param_grid["n_clusters"],
    param_grid["init"],
    param_grid["n_init"],
    param_grid["max_iter"]
))

# Define model

In [ ]:
def evaluate_kmeans(params):
    start = time.time()
    n_clusters, init, n_init, max_iter = params
    
    pipe = Pipeline([
        ("scale", StandardScaler()),
        ("kmeans", KMeans(
            n_clusters=n_clusters,
            init=init,
            n_init=n_init,
            max_iter=max_iter,
            random_state=42
        ))
    ])
    
    labels = pipe.fit_predict(df)

    # silhouette_score
    silhouette = silhouette_score(df, labels)

    # Supervised clustering metrics
    ari = adjusted_rand_score(y, labels) # no need to do label alignment

    execution_time = float(time.time() - start)

    return {
       "n_clusters": n_clusters,
        "init": init,
        "n_init": n_init,
        "max_iter": max_iter,
        "silhouette": silhouette,
        "inertia": pipe.named_steps["kmeans"].inertia_,
        "execution_time": execution_time,
        "adjusted_rand_score": ari
        
    }


results = Parallel(n_jobs=-1, verbose=10)(
    delayed(evaluate_kmeans)(params) for params in param_combinations
    )
results_kmeans =pd.DataFrame(results)
print(results_kmeans)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done  14 out of  40 | elapsed:    7.3s remaining:   13.7s
[Parallel(n_jobs=-1)]: Done  19 out of  40 | elapsed:    7.4s remaining:    8.2s
[Parallel(n_jobs=-1)]: Done  24 out of  40 | elapsed:    7.4s remaining:    4.9s
[Parallel(n_jobs=-1)]: Done  29 out of  40 | elapsed:    7.4s remaining:    2.8s
[Parallel(n_jobs=-1)]: Done  34 out of  40 | elapsed:    7.5s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:    7.6s finished

    n_clusters       init  n_init  max_iter  silhouette     inertia  \
0            2  k-means++      10       300    0.686393  223.732006
1            2  k-means++      10       500    0.686393  223.732006
2            2  k-means++      20       300    0.686393  223.732006
3            2  k-means++      20       500    0.686393  223.732006
4            2     random      10       300    0.686393  223.732006
5            2     random      10       500    0.686393  223.732006
6            2     random      20       300    0.686393  223.732006
7            2     random      20       500    0.686393  223.732006
8            3  k-means++      10       300    0.505931  140.965817
9            3  k-means++      10       500    0.505931  140.965817
10           3  k-means++      20       300    0.505931  140.965817
11           3  k-means++      20       500    0.505931  140.965817
12           3     random      10       300    0.503001  140.968379
13           3     random      10       500    0.503001  140.968379
14           3     random      20       300    0.505931  140.965817
15           3     random      20       500    0.505931  140.965817
16           4  k-means++      10       300    0.356396  114.617886
17           4  k-means++      10       500    0.356396  114.617886
18           4  k-means++      20       300    0.364390  114.388477
19           4  k-means++      20       500    0.364390  114.388477
20           4     random      10       300    0.366002  114.427145
21           4     random      10       500    0.366002  114.427145
22           4     random      20       300    0.359606  114.389544
23           4     random      20       500    0.359606  114.389544
24           5  k-means++      10       300    0.314687   91.295445
25           5  k-means++      10       500    0.314687   91.295445
26           5  k-means++      20       300    0.310471   91.075639
27           5  k-means++      20       500    0.310471   91.075639
28           5     random      10       300    0.321761   91.191970
29           5     random      10       500    0.321761   91.191970
30           5     random      20       300    0.306520   91.059817
31           5     random      20       500    0.306520   91.059817
32           6  k-means++      10       300    0.288970   81.756582
33           6  k-means++      10       500    0.288970   81.756582
34           6  k-means++      20       300    0.267393   80.166732
35           6  k-means++      20       500    0.267393   80.166732
36           6     random      10       300    0.273801   80.204334
37           6     random      10       500    0.273801   80.204334
38           6     random      20       300    0.276074   80.191939
39           6     random      20       500    0.276074   80.191939

    execution_time  adjusted_rand_score
0         0.360030             0.568116
1         0.465214             0.568116
2         0.382376             0.568116
3         0.380118             0.568116
4         0.462941             0.568116
5         0.364472             0.568116
6         0.367026             0.568116
7         0.458965             0.568116
8         0.392162             0.620135
9         0.404037             0.620135
10        0.482543             0.620135
11        0.481851             0.620135
12        0.456438             0.610073
13        0.496891             0.610073
14        0.467088             0.620135
15        0.481482             0.620135
16        0.037486             0.492547
17        0.037187             0.492547
18        0.062437             0.470568
19        0.071376             0.470568
20        0.030358             0.471568
21        0.021724             0.471568
22        0.048898             0.471568
23        0.046877             0.471568
24        0.047106             0.437172
25        0.048101             0.437172
26        0.091737             0.416651
27        0.090209             0.416651
28        0.033076             0.433491
29        0.038842             0.433491
30        0.045603             0.415408
31        0.053474             0.415408
32        0.060895             0.452543
33        0.060885             0.452543
34        0.096967             0.351210
35        0.063185             0.351210
36        0.033213             0.351210
37        0.033372             0.351210
38        0.051381             0.353814
39        0.051713             0.353814